require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  NewCops: enable
  TargetRubyVersion: 2.7.2

Metrics/BlockLength:
  ExcludedMethods: ['describe']
  Max: 50

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

Style/Documentation:
  Enabled: false