---
openapi: 3.0.3
info:
  title: Minato Rails
  version: v1
paths:
  "/v1/blogs":
    post:
      summary: Creates a blog
      tags:
      - Blogs
      parameters: []
      security:
      - bearer_auth: []
      responses:
        '201':
          description: blog created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/blog"
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
        '403':
          description: Not authorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/new_blog"
    get:
      summary: Get the blogs list
      tags:
      - Blogs
      security:
      - bearer_auth: []
      responses:
        '200':
          description: the blogs list
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/blog"
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
  "/v1/blogs/{id}":
    get:
      summary: Retrieves a blog
      tags:
      - Blogs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      security:
      - bearer_auth: []
      responses:
        '200':
          description: the blog found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/blog"
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
        '403':
          description: Not authorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
        '404':
          description: blog not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
    put:
      summary: Updates a blog
      tags:
      - Blogs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      security:
      - bearer_auth: []
      responses:
        '200':
          description: the updated blog
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/blog"
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
        '403':
          description: Not authorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
        '404':
          description: blog not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/new_blog"
    delete:
      summary: Removes a blog
      tags:
      - Blogs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      security:
      - bearer_auth: []
      responses:
        '204':
          description: Removes the blog successfuly
        '401':
          description: Not authorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
        '403':
          description: Not authorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
        '404':
          description: blog not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  schemas:
    blog:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    new_blog:
      type: object
      properties:
        title:
          type: string
        author_id:
          type: integer
      required:
      - title
      - author_id
    error_object:
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
