# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= "#{Settings.database.url}/minato_rails_development" %>

test:
  <<: *default
  url: <%= "#{Settings.database.url}/minato_rails_test" %>

production:
  <<: *default
  url: <%= Settings.database.url %>
