# API specifications settings
api:
  docs:
    auth:
      password: ''
      username: ''
    root: 'swagger'
    versions:
      - default_host: 'localhost:3000'
        description: 'Minato Rails Docs'
        endpoint: '/api-docs/v1/swagger.yaml'
        id: 'v1/swagger.yaml'
        openapi: '3.0.3'
        title: 'Minato Rails'
        version: 'v1'

# CORS settings
cors:
  allowed_origins: '*'

# Database connection url
database:
  url: ''
